# Generated by Django 6.0.4 on 2026-04-23 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_projet', models.CharField(editable=False, max_length=10, unique=True)),
                ('titre', models.CharField(max_length=200)),
                ('lieu', models.CharField(max_length=200)),
                ('annee', models.CharField(max_length=10)),
                ('categorie', models.CharField(choices=[('topographie', 'Topographie'), ('travaux_publics', 'Travaux Publics'), ('construction', 'Construction'), ('hydraulique', 'Hydraulique'), ('cartographie', 'Cartographie'), ('juridique', 'Juridique foncier'), ('amenagement', 'Aménagement'), ('formation', 'Formation'), ('vente', 'Vente matériel'), ('import_export', 'Import-Export'), ('informatique', 'Informatique'), ('bathymetrie', 'Bathymétrie'), ('minier', 'Minier')], default='construction', max_length=30)),
                ('description', models.TextField()),
                ('image_principale', models.ImageField(blank=True, null=True, upload_to='projets/')),
                ('est_publie', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='demandecontact',
            name='annonce',
        ),
        migrations.RemoveField(
            model_name='image',
            name='annonce',
        ),
        migrations.RemoveField(
            model_name='commentaire',
            name='annonce',
        ),
        migrations.AlterModelOptions(
            name='commentaire',
            options={},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={},
        ),
        migrations.RemoveField(
            model_name='demandecontact',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='demandecontact',
            name='traite',
        ),
        migrations.AddField(
            model_name='demandecontact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='demandecontact',
            name='message',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='projets/images/'),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='projet',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='annonces.projet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demandecontact',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='annonces.projet'),
        ),
        migrations.AddField(
            model_name='image',
            name='projet',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='annonces.projet'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Annonce',
        ),
    ]
