# Generated by Django 6.0.4 on 2026-04-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0002_projet_remove_demandecontact_annonce_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['ordre']},
        ),
        migrations.AlterField(
            model_name='projet',
            name='image_principale',
            field=models.ImageField(blank=True, null=True, upload_to='projets/images/'),
        ),
    ]
