# Generated by Django 6.0.4 on 2026-04-25 00:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0003_alter_image_options_alter_projet_image_principale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={},
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='note',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='projet',
            name='categorie',
            field=models.CharField(choices=[('construction', 'Construction'), ('topographie', 'Topographie'), ('amenagement', 'Aménagement'), ('forage', 'Forage'), ('second_oeuvre', 'Second Œuvre'), ('hydraulique', 'Hydraulique'), ('cartographie', 'Cartographie'), ('juridique', 'Juridique foncier'), ('import_export', 'Import-Export'), ('informatique', 'Informatique'), ('bathymetrie', 'Bathymétrie'), ('minier', 'Minier')], default='construction', max_length=30),
        ),
        migrations.AlterField(
            model_name='projet',
            name='image_principale',
            field=models.ImageField(blank=True, null=True, upload_to='projets/'),
        ),
    ]
